# Configuration file for Accelerate
compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: MULTI_GPU
fsdp_config: {}
gpu_ids: all
machine_rank: 0
main_process_ip: null
main_process_port: 29001
main_training_function: main
num_machines: 1
num_processes: 2
